trigger:
  branches:
    include:
    - develop
    - feature/*
  paths:
    include:
    - Infrastructure/Terraform/KeyVault-Secrets
    exclude:
    - Infrastructure/Pipeline

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: DevOps
      type: GitHub
      name: 'KiwirailAzureIntegration/DevOps.Pipelines.Common'
      endpoint: 'GitHub - NikolaiBlackieKiwirail'
      ref: 'refs/heads/main'

variables:
- template: Validation\validation-condition-variables.yaml@DevOps
- name: TerraformVersion 
  value: 1.7.5
- name: TerraformStateFileName
  value: IntegrationFrontEnd.APIM.API.MAS.OMS.KeyVault.Secrets.terraform.tfstate
- name: TerraformWorkingDirectory
  value: '$(System.DefaultWorkingDirectory)/Infrastructure/Terraform/KeyVault-Secrets'
- name: TerraformEnvironmentVariableName
  value: '$(Environment.Name).tfvars'

stages: 
  - stage: DvDeploy
    displayName: 'Deploy to dv'
    jobs:
    - deployment: 'dv'
      variables:
      - group: Azure.IntegrationShared.KV.DV
      - group: Azure.IntegrationShared.NONPROD
      - group: Azure.IntegrationShared.Terraform.DV
      - group: Azure.IntegrationFrontend.APIM.MAS.OMS.Secret
      displayName: 'Deploy Azure.IntegrationFrontend.APIM.MAS.OMS.Secret to resource group on dv' 
      environment: 'dv'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: Deploy\deploy-terraform-init.yaml@DevOps
              parameters:
                terraformVersion: ${{ variables.TerraformVersion }}
                terraformBackendStorageAccountResourceGroupName: '$(TerraformBackendResourceGroup)'
                terraformBackendStorageAccountName: '$(TerraformBackendStorageAccount)'
                terraformBackendBlobContainerName: '$(TerraformBackendContainer)'
                terraformBackendStateFileName: ${{ variables.TerraformStateFileName }}
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureDevopsConnectionName: 'Integration-DevOps-SP-NONPROD'

            - template: Deploy\deploy-terraform-plan.yaml@DevOps
              parameters:
                terraformEnvironmentVariableFileName: '${{ variables.TerraformEnvironmentVariableName }}'
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                terraformCustomCommands: '-var "keyvault_secret_mas_oms_basicsecret=$(MAS.OMS.Secret)" -var "keyvault_secret_mas_oms_basicname=$(MAS.OMS.Name)" -var "keyvault_secret_mas_oms_apikey=$(MAS.OMS.ApiKey)"'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-NONPROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-NONPROD-ClientSecret)

            - template: Deploy\deploy-terraform-apply.yaml@DevOps
              parameters:
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-NONPROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-NONPROD-ClientSecret)

  - stage: TsDeploy
    displayName: 'Deploy to ts'
    condition: ${{ variables.tsCondition }}
    jobs:
    - deployment: 'ts'
      variables:
      - group: Azure.IntegrationShared.KV.TS
      - group: Azure.IntegrationShared.NONPROD
      - group: Azure.IntegrationShared.Terraform.TS
      - group: Azure.IntegrationFrontend.APIM.MAS.OMS.Secret
      displayName: 'Deploy Azure.IntegrationFrontend.APIM.MAS.OMS.Secret to resource group on ts' 
      environment: 'ts'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: Deploy\deploy-terraform-init.yaml@DevOps
              parameters:
                terraformVersion: ${{ variables.TerraformVersion }}
                terraformBackendStorageAccountResourceGroupName: '$(TerraformBackendResourceGroup)'
                terraformBackendStorageAccountName: '$(TerraformBackendStorageAccount)'
                terraformBackendBlobContainerName: '$(TerraformBackendContainer)'
                terraformBackendStateFileName: ${{ variables.TerraformStateFileName }}
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureDevopsConnectionName: 'Integration-DevOps-SP-NONPROD'

            - template: Deploy\deploy-terraform-plan.yaml@DevOps
              parameters:
                terraformEnvironmentVariableFileName: '${{ variables.TerraformEnvironmentVariableName }}'
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                terraformCustomCommands: '-var "keyvault_secret_mas_oms_basicsecret=$(MAS.OMS.Secret)" -var "keyvault_secret_mas_oms_basicname=$(MAS.OMS.Name)" -var "keyvault_secret_mas_oms_apikey=$(MAS.OMS.ApiKey)"'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-NONPROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-NONPROD-ClientSecret)

            - template: Deploy\deploy-terraform-apply.yaml@DevOps
              parameters:
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-NONPROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-NONPROD-ClientSecret)

  - stage: Ut_AUE_Deploy
    displayName: 'Deploy to ut australia east'
    condition: ${{ variables.utCondition }}
    jobs:
    - deployment: 'ut_aue'
      variables:
      - group: Azure.IntegrationShared.KV.AUE.UT
      - group: Azure.IntegrationShared.AUE.PROD
      - group: Azure.IntegrationShared.Terraform.AUE.UT
      - group: Azure.IntegrationFrontend.APIM.MAS.OMS.Secret
      displayName: 'Deploy Azure.IntegrationFrontend.APIM.MAS.OMS.Secret to resource group on ut-aue' 
      environment: 'ut-aue'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: Deploy\deploy-terraform-init.yaml@DevOps
              parameters:
                terraformVersion: ${{ variables.TerraformVersion }}
                terraformBackendStorageAccountResourceGroupName: '$(TerraformBackendResourceGroup)'
                terraformBackendStorageAccountName: '$(TerraformBackendStorageAccount)'
                terraformBackendBlobContainerName: '$(TerraformBackendContainer)'
                terraformBackendStateFileName: ${{ variables.TerraformStateFileName }}
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureDevopsConnectionName: 'Integration-DevOps-SP-UAT'

            - template: Deploy\deploy-terraform-plan.yaml@DevOps
              parameters:
                terraformEnvironmentVariableFileName: '${{ variables.TerraformEnvironmentVariableName }}'
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                terraformCustomCommands: '-var "keyvault_secret_mas_oms_basicsecret=$(MAS.OMS.Secret)" -var "keyvault_secret_mas_oms_basicname=$(MAS.OMS.Name)" -var "keyvault_secret_mas_oms_apikey=$(MAS.OMS.ApiKey)"'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-UAT-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-UAT-ClientSecret)

            - template: Deploy\deploy-terraform-apply.yaml@DevOps
              parameters:
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-UAT-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-UAT-ClientSecret)

  - stage: Ut_AUS_Deploy
    displayName: 'Deploy to ut australia south east'
    condition: ${{ variables.utCondition }}
    jobs:
    - deployment: 'ut_aus'
      variables:
      - group: Azure.IntegrationShared.KV.AUS.UT
      - group: Azure.IntegrationShared.AUS.PROD
      - group: Azure.IntegrationShared.Terraform.AUS.UT
      - group: Azure.IntegrationFrontend.APIM.MAS.OMS.Secret
      displayName: 'Deploy Azure.IntegrationFrontend.APIM.MAS.OMS.Secret to resource group on ut-aus' 
      environment: 'ut-aus'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: Deploy\deploy-terraform-init.yaml@DevOps
              parameters:
                terraformVersion: ${{ variables.TerraformVersion }}
                terraformBackendStorageAccountResourceGroupName: '$(TerraformBackendResourceGroup)'
                terraformBackendStorageAccountName: '$(TerraformBackendStorageAccount)'
                terraformBackendBlobContainerName: '$(TerraformBackendContainer)'
                terraformBackendStateFileName: ${{ variables.TerraformStateFileName }}
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureDevopsConnectionName: 'Integration-DevOps-SP-UAT'

            - template: Deploy\deploy-terraform-plan.yaml@DevOps
              parameters:
                terraformEnvironmentVariableFileName: '${{ variables.TerraformEnvironmentVariableName }}'
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                terraformCustomCommands: '-var "keyvault_secret_mas_oms_basicsecret=$(MAS.OMS.Secret)" -var "keyvault_secret_mas_oms_basicname=$(MAS.OMS.Name)" -var "keyvault_secret_mas_oms_apikey=$(MAS.OMS.ApiKey)"'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-UAT-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-UAT-ClientSecret)

            - template: Deploy\deploy-terraform-apply.yaml@DevOps
              parameters:
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-UAT-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-UAT-ClientSecret)

  - stage: Pd_AUE_Deploy
    displayName: 'Deploy to pd australia east'
    condition: ${{ variables.pdCondition }}
    jobs:
    - deployment: 'pd_aue'
      variables:
      - group: Azure.IntegrationShared.KV.AUE.PD
      - group: Azure.IntegrationShared.AUE.PROD
      - group: Azure.IntegrationShared.Terraform.AUE.PD
      - group: Azure.IntegrationFrontend.APIM.MAS.OMS.Secret.PD
      displayName: 'Deploy Azure.IntegrationFrontend.APIM.MAS.OMS.Secret to resource group on pd-aue' 
      environment: 'pd-aue'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: Deploy\deploy-terraform-init.yaml@DevOps
              parameters:
                terraformVersion: ${{ variables.TerraformVersion }}
                terraformBackendStorageAccountResourceGroupName: '$(TerraformBackendResourceGroup)'
                terraformBackendStorageAccountName: '$(TerraformBackendStorageAccount)'
                terraformBackendBlobContainerName: '$(TerraformBackendContainer)'
                terraformBackendStateFileName: ${{ variables.TerraformStateFileName }}
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureDevopsConnectionName: 'Integration-DevOps-SP-PROD'

            - template: Deploy\deploy-terraform-plan.yaml@DevOps
              parameters:
                terraformEnvironmentVariableFileName: '${{ variables.TerraformEnvironmentVariableName }}'
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                terraformCustomCommands: '-var "keyvault_secret_mas_oms_basicsecret=$(MAS.OMS.Secret)" -var "keyvault_secret_mas_oms_basicname=$(MAS.OMS.Name)" -var "keyvault_secret_mas_oms_apikey=$(MAS.OMS.ApiKey)"'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-PROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-PROD-ClientSecret)

            - template: Deploy\deploy-terraform-apply.yaml@DevOps
              parameters:
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-PROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-PROD-ClientSecret)

  - stage: Pd_AUS_Deploy
    displayName: 'Deploy to pd australia south east'
    condition: ${{ variables.pdCondition }}
    jobs:
    - deployment: 'pd_aus'
      variables:
      - group: Azure.IntegrationShared.KV.AUS.PD
      - group: Azure.IntegrationShared.AUS.PROD
      - group: Azure.IntegrationShared.Terraform.AUS.PD
      - group: Azure.IntegrationFrontend.APIM.MAS.OMS.Secret.PD
      displayName: 'Deploy Azure.IntegrationFrontend.APIM.MAS.OMS.Secret to resource group on pd-aus' 
      environment: 'pd-aus'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: Deploy\deploy-terraform-init.yaml@DevOps
              parameters:
                terraformVersion: ${{ variables.TerraformVersion }}
                terraformBackendStorageAccountResourceGroupName: '$(TerraformBackendResourceGroup)'
                terraformBackendStorageAccountName: '$(TerraformBackendStorageAccount)'
                terraformBackendBlobContainerName: '$(TerraformBackendContainer)'
                terraformBackendStateFileName: ${{ variables.TerraformStateFileName }}
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureDevopsConnectionName: 'Integration-DevOps-SP-PROD'

            - template: Deploy\deploy-terraform-plan.yaml@DevOps
              parameters:
                terraformEnvironmentVariableFileName: '${{ variables.TerraformEnvironmentVariableName }}'
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                terraformCustomCommands: '-var "keyvault_secret_mas_oms_basicsecret=$(MAS.OMS.Secret)" -var "keyvault_secret_mas_oms_basicname=$(MAS.OMS.Name)" -var "keyvault_secret_mas_oms_apikey=$(MAS.OMS.ApiKey)"'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-PROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-PROD-ClientSecret)

            - template: Deploy\deploy-terraform-apply.yaml@DevOps
              parameters:
                terraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
                azureSubscription: $(subscriptionId)
                azureTenantId: $(tenantId)
                azureServicePrincipalClientId: $(Integration-DevOps-SP-PROD-ClientId)
                azureServicePrincipalSecret: $(Integration-DevOps-SP-PROD-ClientSecret)